name: Deploy to GitHub pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test and generate files
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm ci
    - name: Install antlr4
      - run:  wget https://www.antlr.org/download/antlr-4.9.2-complete.jar
      - run: alias antlr4='java -jar antlr-4.9.2-complete.jar'
    - run: npm run grammar
    - run: npm test
    - run: npm run build
    - name: Commit and push
      run: |
        cd docs/
        git add *
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m 'Deploy'
        git push

